### PR TITLE
Ankita k

### PR DESCRIPTION
**Pull request by AnkitaKum03**
Please merge my changes. Ankita Kumar.

### CODE REVIEW

**Comment by ryanwlin** [comment]
the classroom.java file doesn't have the latest code added

**Comment by AnkitaKum03** [comment]
My seat is the in the correct place, another student has placed the seat in my area. I think it's Katie Cheng.

**Comment by AnkitaKum03** [comment]
I left a comment in the Github thread about this, but my image is in the correct place. Another student, Katie Cheng has put her Image in the area my image was supposed to be in. Because her pull request was accepted before mine, I received this email. I contacted Katie about this.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Review by SaachiT — APPROVED** [review]

**Comment by AnkitaKum03** [comment]
Hi,
Why is my pull request still open? I got an email saying that you were trying to merge my branch and the pull request was approved. I recloned the project from GitHub and my code is still not on the greenfoot project. Also , I still see Katie’s image in my spot for the seating chart which was originally causing the problems with my code. Also if you accepted the pull request then why are my changes not in the master?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by SaachiT** [comment]
i just emailed her to let her know she is in the wrong seat.

**Pull request merged**
