### PR TITLE
WaleedRydhan files

### PR DESCRIPTION
**Pull request by wrydhan**
Adding my code, images, and sound.

### CODE REVIEW

**Review by ryanwlin — COMMENTED** [review]
looks good to me

**Review by SaachiT — CHANGES_REQUESTED** [review]
Don't delete other people's code on classroom.java

**Review by SaachiT — APPROVED** [review]

**Comment by workingSpear** [comment]
currently sick so can't fix as I don't have git or  java IDEs  on this PC so saachi or ryan will have to fix this

**Comment by ryanwlin** [comment]
just fixed the classroom.java file and committed and pushed it to the branch so please submit another pull request so we can merge #

**Pull request merged**
